version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore WebApplication1/WebApplication1.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output WebApplication1/WebApplication1.csproj
artifacts:
  files:
    - WebApplication1/build_output/**/*